url: https://www.uwspianoschool.com
baseurl: /uwspianoschool/

# Site settings
title: UWS Piano School
email: your-email@domain.com
description: "Write an awesome description for your piano school. This will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Sean Carmichael
  pic: 1
  position: Doctor of Piano
  bio: Four score and seven years ago, a man was born. Well he was originally a baby, but now he is a man. He knows the keys and will bring new meaning to the phrase "take me to church"!
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/sean-carmichael-313362107/
    - title: facebook
      url: #
    - title: twitter
      url: #


- name: Nadezhda Christova Carmichael
  pic: 2
  position: Master of the Keys
  bio: Nadia has played the piano since she was a little girl. Now she still plays the piano. She will teach ya!
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/nadezhda-christova-0b8b05110/
    - title: facebook
      url: #
    - title: twitter
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/uwspianoschool
  - title: facebook
    url: https://facebook.com/uwspianoschool

# Postal address (add as many lines as necessary)
address:
  - line: 23 W 71st St
  - line: New York, NY 10023

# Build settings
markdown: kramdown
permalink: pretty
